obj-$(CONFIG_TOUCHSCREEN_ILI210X_FIH)       += ilitek_fih/
obj-$(CONFIG_TOUCHSCREEN_FTS_FIH) += focaltech_touch_fih/
obj-$(CONFIG_TOUCHSCREEN_NT36xxx_FIH) += nt36xxx_fih/
obj-$(CONFIG_TOUCHSCREEN_GX_FIH) += gt1x_fih/
obj-$(CONFIG_TOUCHSCREEN_GT9XX_FIH) += gt9xx_fih/
obj-$(CONFIG_TOUCHSCREEN_FT8719_FIH) += focaltech_touch_8719_fih/
