#
# Makefile for the goodix touchscreen drivers.
#
obj-$(CONFIG_TOUCHSCREEN_GX_FIH)	+=  gt1x_extents.o gt1x_generic.o gt1x_tools.o gt1x.o gt1x_update.o
obj-$(CONFIG_TOUCHSCREEN_GX_FIH_TESTS)	+= gt1x_test.o test_function.o
