#
# Makefile for the goodix touchscreen drivers.
#
obj-$(CONFIG_TOUCHSCREEN_GX_FIH)	+=  gt1x_extents.o
obj-$(CONFIG_TOUCHSCREEN_GX_FIH)	+=  gt1x_generic.o
obj-$(CONFIG_TOUCHSCREEN_GX_FIH)	+=  gt1x_tools.o
obj-$(CONFIG_TOUCHSCREEN_GX_FIH)	+=  gt1x.o
obj-$(CONFIG_TOUCHSCREEN_GX_FIH)	+=  gt1x_update.o
obj-$(CONFIG_TOUCHSCREEN_GX_FIH)	+=  gt1x_test.o
obj-$(CONFIG_TOUCHSCREEN_GX_FIH)	+=  test_function.o
