#
# Makefile for the Goodix gt9xx touchscreen driver.
#
#subdir-ccflags-y += -DDEBUG
obj-$(CONFIG_TOUCHSCREEN_GT9XX_FIH)		+= gt9xx.o
obj-$(CONFIG_TOUCHSCREEN_GT9XX_FIH_UPDATE)	+= gt9xx_update.o
obj-$(CONFIG_TOUCHSCREEN_GT9XX_FIH_TOOL)	+= goodix_tool.o
