#Fihtdc@Alan, add
dtb-$(CONFIG_FIH_SDM630_SDM660_PROJS) += sdm660-mtp.dtb \
 	sdm630-mtp.dtb \
	sdm660-qrd.dtb \
 	sdm630-pm660a-qrd.dtb \
	sdm660-cdp-c1n-preEVT.dtb \
	sdm660-cdp-c1n-EVT.dtb \
	sdm660-mtp-c1n-preEVT.dtb \
	sdm660-mtp-c1n-EVT.dtb \
	sdm660-mtp-c1n-EVT2.0.dtb \
	sdm660-mtp-c1n-EVT2.1.dtb \
	sdm660-mtp-pl2-preEVT.dtb \
	sdm630-cdp-c1n-preEVT.dtb \
	sdm630-cdp-c1n-EVT.dtb \
	sdm630-mtp-c1n-preEVT.dtb \
	sdm630-mtp-c1n-EVT.dtb \
	sdm630-mtp-c1n-EVT2.0.dtb \
	sdm630-mtp-c1n-EVT2.1.dtb \
	sdm630-mtp-pl2-preEVT.dtb \
	sdm630-mtp-pl2-EVT1.5.dtb \
	sdm630-mtp-pl2-EVT1.5-CD.dtb \
	sdm630-mtp-pl2-dvt.dtb \
	sdm660-mtp-b2n-preEVT.dtb \
	sdm660-mtp-b2n-EVT.dtb \
	sdm660-mtp-b2n-EVT1.5.dtb \
	sdm660-mtp-b2n-DVT-QC.dtb \
	sdm660-mtp-b2n-DVT-TI.dtb \
	sdm660-mtp-drg-preEVT.dtb \
	sdm636-mtp-drg-preEVT.dtb \
	sdm636-mtp-b2n-preEVT.dtb \
	sdm636-mtp-ctl-EVT.dtb \
	sdm636-mtp-drg-EVT.dtb \
	sdm636-mtp-ctl-DVT.dtb \
	sdm636-mtp-drg-DVT1.5.dtb \
	sdm660-mtp-drg-pro-EVT.dtb \
	sdm636-mtp-hc1-preEVT.dtb \
	sdm660-mtp-tas-preEVT.dtb \
	sdm660-mtp-tas-EVT.dtb \
	sdm660-mtp-tas-PVT.dtb \
	sdm660-mtp-tas-MP.dtb \
	sdm630-cdp-s2-evt.dtb \
	sdm630-cdp-s2-dvt.dtb \
	sdm630-mtp-s2-evt.dtb \
	sdm630-mtp-s2-dvt.dtb \
	sdm630-mtp-s2_eu-dvt.dtb

always		:= $(dtb-y)
subdir-y	:= $(dts-dirs)
clean-files	:= *.dtb
